version: '3.9'

volumes:
  grafana: {}

networks:
  backbone: 
    driver: bridge

services:
  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    networks:
      - backbone
    expose:
      - '8080'

  grafana:
    image: grafana/grafana:5.1.0
    container_name: grafana
    networks:
      - backbone
    expose:
      - '3000'

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl.conf:/etc/nginx/includes/ssl.conf:ro
      - ./ssl:/etc/ssl/:ro
    networks:
      - backbone
    ports:
      - 443:443

  prometheus:
    image: 'prom/prometheus:latest'
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backbone
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - '9090'
